version: 1
labels:
  - label: "documentation"
    files:
      - "*.md"
  - label: "enhancement"
    files:
      - "*.yml"
      - "*.yaml"
  - label: "C"
    files:
      - "*.c"
  - label: "C#"
    files:
      - "*.cs"
  - label: "C++"
    files:
      - "*.cpp"
  - label: "Go"
    files:
      - "*.go"
  - label: "Java"
    files:
      - "*.java"
  - label: "Python"
    files:
      - "*.py"
  
